### ISSUE TITLE
Query bolock return null hash

### ISSUE THREAD

**Issue by Senna46** [SunriseLayer/sunrise-app#10]
square_size is fin e, but hash is not set correctly
```
$ sunrised q block --type=height 1
data:
  hash: null
  square_size: "1"
  txs: []
```

**Comment by Senna46** [comment]
Expected
```
$ celestia-appd q block 1 --node http://rpc-celestia.alphab.ai:26657
{"block_id":{"hash":"6BE39EFD10BA412A9DB5288488303F5DD32CF386707A5BEF33617F4C43301872","parts":{"total":1,"hash":"5CC83B67E3160862FBEF613A1C7A37C87E664EA1A6AB61C3CB546EE281F9FE3F"}},"block":{"header":{"version":{"block":"11","app":"1"},"chain_id":"celestia","height":"1","time":"2023-10-31T14:00:00Z","last_block_id":{"hash":"","parts":{"total":0,"hash":""}},"last_commit_hash":"E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855","data_hash":"3D96B7D238E7E0456F6AF8E7CDF0A67BD6CF9C2089ECB559C659DCAA1F880353","validators_hash":"83387942B3A526EA149EAF52ADCD3A72F4676F574516D8E22EB0B8F9CFFD56F5","next_validators_hash":"83387942B3A526EA149EAF52ADCD3A72F4676F574516D8E22EB0B8F9CFFD56F5","consensus_hash":"C0B6A634B72AE9687EA53B6D277A73ABA1386BA3CFC6D0F26963602F7F6FFCD6","app_hash":"E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855","last_results_hash":"E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855","evidence_hash":"E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855","proposer_address":"07E5EAFEE033B9897E4136DDF30D9715E6AC63AE"},"data":{"txs":null,"square_size":"1"},"evidence":{"evidence":null},"last_commit":{"height":"0","round":0,"block_id":{"hash":"","parts":{"total":0,"hash":""}},"signatures":null}}}
```

sunrise
```
# sunrised q block --type=height 1
data:
  hash: null
  square_size: "0"
  txs:
  - PZa30jjn4EVvavjnzfCme9bPnCCJ7LVZxlncqh+IA1M=
  - AAAAAAAAAAE=
evidence:
  evidence: []
header:
  app_hash: 47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=
  chain_id: sunrise-private-1
  consensus_hash: BICRvH3cKD93v7+R1zxE2ljD34qcvIZ0Bdi389qtoi8=
  data_hash: SBECNPS9wku+Gu21yV/ePrhiDqUlKlPDXcE+xz/sQBQ=
  evidence_hash: 47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=
  height: "1"
  last_block_id:
    hash: ""
    part_set_header:
      hash: ""
      total: 0
  last_commit_hash: 47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=
  last_results_hash: 47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=
  next_validators_hash: AInkweorKyIC7/XNzj6lElSmkAjDCQS8hhUllJkrDyA=
  proposer_address: v1c2BwLQfiaIsehhGfIf95hCWac=
  time: "2024-04-15T15:05:01.186758780Z"
  validators_hash: AInkweorKyIC7/XNzj6lElSmkAjDCQS8hhUllJkrDyA=
  version:
    app: "0"
    block: "11"
last_commit:
  block_id:
    hash: ""
    part_set_header:
      hash: ""
      total: 0
  height: "0"
  round: 0
  signatures: []
```
